version: '3'

services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - bot-network

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  redis-data: 